name: enade-py
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.8
  - pip
  - pandas
  - ipython
  - matplotlib
  - seaborn
  - scikit-learn
  - pip:
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     - docformatter
     - optuna
  # for development only (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
  - dvc
  - pydrive2
  - yapf
  - isort
  - flake8
  - bandit
  - pycodestyle
  - mlxtend
